### ISSUE TITLE
Testing the new archiving and exporter flow

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-dev-team#168]
As a data wrangler I need to test that a project proceeds through different states as expected when a valid project is submitted.

The three flows are:
### **1. Submit to HCA and to archives**
Valid -> Submitted -> Processing -> Archiving -> Archived -> Exporting -> Exported -> Cleanup (?) -> Completed

Checked with project: https://ui.ingest.dev.archive.data.humancellatlas.org/projects/detail?uuid=ade1291d-8636-4e7f-abd7-49fd4dd1f2b1

#### Acceptance Criteria
- [x] project progresses through states as expected
- [x] Archiving state produces as a manifest
- [x] Exporting state exports to GCP
- [x] Cleanup deletes the ingest bucket

### **2. Submit to HCA only**
Valid -> Submitted -> Exporting -> Exported -> Cleanup (?) -> Completed

#### Acceptance Criteria
- [x] project progresses through states as expected
- [x] Exporting state exports to GCP
- [x] Cleanup deletes the ingest bucket

### **3. Submit to Archives only**
Valid -> Submitted -> Processing -> Archiving -> Archived -> cleanup ? -> Completed?

#### Acceptance Criteria
- [x] User should not be able to submit with "delete upload area" selected
- [x] Project progresses through states as expected
- [x] Archiving state produces as a manifest
- [x] Project is not exported to GCP
- [x] Button to subsequently export to GCP exists
- [x] Button to subsequently export to GCP works
- [x] Cleanup deletes the ingest bucket

**Comment by mshadbolt** [comment]
@aaclan-ebi if we do submissions in dev or staging does it submit using to the test instance of DSP (and by extension the test instances of biosamples, biostudies and ena)?

**Comment by aaclan-ebi** [comment]
yup! I'm not sure for all archives, but for BioSamples and ENA it's possible. The data won't last for a day, their test env db get's refreshed daily i think.

**Comment by aaclan-ebi** [comment]
For BioSamples: http://wwwdev.ebi.ac.uk/biosamples/

For ENA:
Webin Portal: https://wwwdev.ebi.ac.uk/ena/submit/webin/login
Webin Interactive:  https://wwwdev.ebi.ac.uk/ena/submit/sra/#home
 
> Dev domain wwwdev.ebi.ac.uk points to TEST environment not dev, you can query directly in the test DB or using the following interactive applications:
We'll use TEST env of DSP so it should submit to TEST env of archives.
> Test submissions are overwritten every 24hours (at 3am) with production data.
this is according to a previous email from Josue from ENA (already left)

**Comment by aaclan-ebi** [comment]
Hi! @mshadbolt @rays22  The new submission state transition flow (excluding archiving) should be ready to test in dev, https://ui.ingest.dev.archive.data.humancellatlas.org/home

You could skip archiving for now but If you chose to include archiving when you submit the submission, the submission will transition to `Archiving` but nothing will happen yet, it's still a manual process atm. You can force the submission to go to Archived by:

```
curl -X PUT https://api.ingest.dev.archive.data.humancellatlas.org/submissionEnvelopes/5ee8baa4138e2b208b5994f7/archivedEvent
```

The UI changes are described here: https://docs.google.com/document/d/11NAxNDQ5m-32aEgDkvkwYPWd4pjexspbbncDtpdpjk4/edit Let me know if you see any issues or feedback here.

**Comment by mshadbolt** [comment]
So the possible paths a project could take once a user has a valid submission with uploaded data files are:
1. Submit project to both archives and HCA
- project goes first into 'archiving' status  
   - How do we test this is successful? Should we check if a manifest is created (if this is what should happen, I am not really sure)
- We trigger the project to to 'archived' status to simulate actual archiving
  - @clairerye 's comment above seemed to hint that she actually wanted us to carry out the archiving process in the test instances of DSP, is that true or should we kick it into archiving as Alegria describes above?
- project should automatically get exported to dcp staging area
  - how do we check that the project was exported?

2. Submit project to HCA only
- project gets exported to dcp staging area
  - how do we check that the project was exported?

3. Submit project to archives only
- Same questions as above for 1. i.e. if we have to carry out the archiving process in test environments or manually set the 'archived' status
- Project should not go to archives
  - How do we check the project **hasn't** been exported to dcp staging area?

**Comment by aaclan-ebi** [comment]
Very good questions, @mshadbolt !

Yeah #1 is definitely not possible to test yet.

> So the possible paths a project could take once a user has a valid submission with uploaded data files are:
> 1. Submit project to both archives and HCA
> - project goes first into 'archiving' status  
>    - How do we test this is successful? Should we check if a manifest is created (if this is what should happen, I am not really sure)
> - We trigger the project to go to 'archived' status to simulate actual archiving
>   - @clairerye 's comment above seemed to hint that she actually wanted us to carry out the archiving process in the test instances of DSP, is that true or should we kick it into archived as @aaclan-ebi describes above?

There is a manual process for archiving now documented in the doc https://docs.google.com/document/d/1S4fyCSqB3nLrCUssNMwSp6ff8tmeipMi_slnXW2Lrq4/edit 

You could do the actual archiving (undergo all the manual steps and submit to DSP) and the metadata will be updated with accessions in Ingest. That's implemented in the script which you need to manually run atm. You could verify that after successful submission to DSP.  You would still have to manually set the Archived because i haven't added that to happen in the script (sorry about that, I will add those soon :)).

After setting the submission to Archived, depending on the submit actions/options you selected, the submission will : 
1. if you checked the option to submit to hca
the submission will automatically transition to Exporting -> Exported
1.a. and  if you checked delete upload area
the submission will automatically transition to Exported -> Cleanup -> Completed
2. if you didn't check the option to submit to hca
the submission will stay in Archived and `Submit to HCA` button will appear

I'm doing some changes to be able to track the DSP submission in Ingest, it should be possible to generate a nicer report once I'm done with those changes. But that's not completed yet. Actually, i'm not sure yet if that is in scope of the transition flow. But I will aim to finish those this sprint.

> - project should automatically get exported to dcp staging area with accessions
>   - how do we check that the project was exported?
>   - how do we check that accessions are included in the exported project if we don't carry out the archiving?

I think you could check the terra buckets if the new accessions (from manual archiving atm) are in the metadata json's.

> 2. Submit project to HCA only
> - project gets exported to dcp staging area
>   - how do we check that the project was exported?
> - project shouldn't get pushed to archives
>   - how do we check that archiving process wasn't initiated?

To verify that the project isn't pushed to archives, you could check that the metadata won't have any new accessions. The exported metadata to terra won't have accessions as well.

Once I finished the changes for tracking DSP submission and its entities, you would also be able to verify that there'll be no record of any DSP submission in Ingest.

> 3. Submit project to archives only
> - Same questions as above for 1. i.e. if we have to carry out the archiving process in test environments or manually set the 'archived' status
> - Project should not go to DCP staging area
>   - How do we check the project **hasn't** been exported to dcp staging area?

The project won't be in terra bucket. I'm not sure about this as well, if terra has a better way for user to see the data in a test environment. Obviously, not all users will be given access to the terra buckets. Might be best to confirm with @rolando-ebi

**Comment by aaclan-ebi** [comment]
This is how I imagine #1 to be

https://mermaid-js.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgVXNlci0-PkluZ2VzdCBDb3JlOiBoYXMgYSBWQUxJRCBzdWJtaXNzaW9uXG4gICAgVXNlci0-PkluZ2VzdCBDb3JlOiBzdWJtaXNzaW9uIGlzIFNVQk1JVFRFRFxuICAgIEluZ2VzdCBDb3JlIC0-PiBJbmdlc3QgRXhwb3J0ZXI6IGV4cG9ydHMgbWFuaWZlc3RzLCBQUk9DRVNTSU5HIHN1Ym1pc3Npb25cbiAgICBJbmdlc3QgRXhwb3J0ZXIgLT4-IEluZ2VzdCBDb3JlOiBzdWJtaXNzaW9uIGlzIHNldCB0byBBUkNISVZJTkdcbiAgICBJbmdlc3QgQ29yZSAtPj4gSW5nZXN0IEFyY2hpdmVyOiB0cmlnZ2VycyBhcmNoaXZpbmdcbiAgICBhY3RpdmF0ZSBJbmdlc3QgQXJjaGl2ZXJcbiAgICBJbmdlc3QgQXJjaGl2ZXItLT4-IEluZ2VzdCBBcmNoaXZlcjogY29udmVydHMgSENBIG1ldGFkYXRhIHRvIGFyY2hpdmUgZW50aXRpZXNcbiAgICBcbiAgICBJbmdlc3QgQXJjaGl2ZXItLT4-IERTUDogIGNyZWF0ZSBzdWJtaXNzaW9uIGFuZCBlbnRpdGllc1xuICAgIFxuICAgIGFjdGl2YXRlIERTUFxuICAgIERTUC0tPj5EU1A6IHZhbGlkYXRpb25cblxuICAgIFVzZXIgLT4-IEluZ2VzdCBBcmNoaXZlcjogY2hlY2sgaWYgZmlsZSB1cGxvYWQgcGxhbiBpcyBhbHJlYWR5IGF2YWlsYWJsZVxuICAgIFVzZXIgLT4-IEVCSSBDbHVzdGVyIDogcGFzcyB0aGUgZmlsZSB1cGxvYWQgcGxhbiB0byBydW4gYSBzY3JpcHQgdG8gdHJpZ2dlciBmaWxlIGFyY2hpdmVyIGpvYnNcbiAgICBFQkkgQ2x1c3RlciAtLT4-IEluZ2VzdCBGaWxlIEFyY2hpdmVyIEpvYnM6IHRyaWdnZXJzIG11bHRpcGxlIGpvYnNcbiAgICBhY3RpdmF0ZSBJbmdlc3QgRmlsZSBBcmNoaXZlciBKb2JzXG4gICAgSW5nZXN0IEZpbGUgQXJjaGl2ZXIgSm9icyAtLT4-IEluZ2VzdCBGaWxlIEFyY2hpdmVyIEpvYnM6IGVhY2ggam9iIHdpbGwgZ2V0IGZpbGVzIGZyb20gczMgdXBsb2FkIGFyZWFzLCBkbyBiYW0gY29udmVyc2lvblxuICAgIEluZ2VzdCBGaWxlIEFyY2hpdmVyIEpvYnMgLS0-PiBEU1AgOiB1cGxvYWRzIGRhdGEgZmlsZXMgXG4gICAgZGVhY3RpdmF0ZSBJbmdlc3QgRmlsZSBBcmNoaXZlciBKb2JzXG4gICAgRFNQIC0tPj4gRFNQIDogdmFsaWRhdGlvblxuICAgIFVzZXIgLT4-IEluZ2VzdCBBcmNoaXZlciA6IHJldHJpZXZlcyB2YWxpZGF0aW9uIHJlcG9ydFxuICAgIEluZ2VzdCBBcmNoaXZlciAtPj4gRFNQOiByZXRyaWV2ZXMgdmFsaWRhdGlvbiByZXN1bHRcbiAgICBEU1AgLT4-IEluZ2VzdCBBcmNoaXZlcjogcmV0cmlldmVzIHZhbGlkYXRpb24gcmVzdWx0XG4gICAgSW5nZXN0IEFyY2hpdmVyLT4-IFVzZXI6IHJldHVybiB2YWxpZGF0aW9uIHJlcG9ydFxuICAgIFVzZXIgLT4-IEluZ2VzdCBBcmNoaXZlcjogY2hlY2tzIGFueSB2YWxpZGF0aW9uIGVycm9ycywgZml4IGFueSBlcnJvcnNcbiAgICBJbmdlc3QgQXJjaGl2ZXIgLS0-PiBEU1A6IHVwZGF0ZXMgZW50aXRpZXNcbiAgICBEU1AgLS0-PiBEU1AgOiB2YWxpZGF0aW9uXG4gICAgVXNlciAtPj4gSW5nZXN0IEFyY2hpdmVyIDogcmV0cmlldmVzIHZhbGlkYXRpb24gcmVwb3J0XG4gICAgSW5nZXN0IEFyY2hpdmVyLT4-IFVzZXI6IHJldHVybiB2YWxpZGF0aW9uIHJlcG9ydFxuICAgIFVzZXIgLT4-IEluZ2VzdCBBcmNoaXZlcjogY29uZmlybSB0byBzdWJtaXRcbiAgICBJbmdlc3QgQXJjaGl2ZXIgLS0-PiBEU1A6IHNldCBzdWJtaXNzaW9uIHRvIFNVQk1JVFRFRCBpZiBzdWJtaXR0YWJsZVxuICAgIFxuICAgIERTUC0tPj5EU1AgOiBzdWJtaXRzIHRvIGFyY2hpdmVzXG5cbiAgICBEU1AtLT4-SW5nZXN0IEFyY2hpdmVyIDogcHJvY2Vzc2luZyByZXN1bHRzXG4gICAgSW5nZXN0IEFyY2hpdmVyLS0-PiBJbmdlc3QgQ29yZSA6IHVwZGF0ZSBtZXRhZGF0YSB3aXRoIGFjY2Vzc2lvbnNcbiAgICBJbmdlc3QgQXJjaGl2ZXItLT4-IEluZ2VzdCBDb3JlIDogc2V0IHN1Ym1pc3Npb24gc3RhdGUgdG8gQXJjaGl2ZWRcbiAgICBkZWFjdGl2YXRlIERTUFxuICAgIFVzZXIgLT4-IEluZ2VzdCBDb3JlIDogdmlldyBtZXRhZGF0YSB1cGRhdGVkIHdpdGggYWNjZXNzaW9uXG5cdGRlYWN0aXZhdGUgSW5nZXN0IEFyY2hpdmVyIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0

**Comment by aaclan-ebi** [comment]
Maybe not the UI components yet, but endpoints that the user could check to download file, get validation result in json, submit, and view accessions report.

And just want to note that those functionalities should be already possible in the Archiver script / manual process.

**Comment by aaclan-ebi** [comment]
btw, i added screenshots in ticket #154

**Comment by mshadbolt** [comment]
@clairerye are you able to confirm whether you want us to go through the full archiving process as part of this testing?

**Comment by clairerye** [comment]
@mshadbolt  Yes please, assuming that can be done today, and there isn't a good reason not too? I think dummy files are fine and do we have the small spreadsheet used for integration tests that will mean we are not waiting hours on file transfer?

**Comment by aaclan-ebi** [comment]
I updated the with config for running in DSP TEST env https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit?ts=5eea61cb&pli=1#heading=h.eeyjdjt197l9

Just want to note that you should also use a different archiver docker image (since changes in the archiver isn't merged to master yet, master image is also being used by operations team (Alexie et al) at the moment so don't want to touch master for now)  

Here's the modified command:

```
docker run -v $PWD:/app/output \
--env INGEST_API_URL=https://api.ingest.archive.data.humancellatlas.org/ \
--env DSP_API_URL=https://submission-test.ebi.ac.uk \
--env ONTOLOGY_API_URL=https://www.ebi.ac.uk/ols \
--env AAP_API_URL=https://explore.api.aai.ebi.ac.uk/auth \
--env AAP_API_DOMAIN=<aap_domain> \
--env AAP_API_USER=<aap_user> \
--env AAP_API_PASSWORD=<aap_password> \
quay.io/ebi-ait/ingest-archiver:feature_ingest-archive-entities-cli \
--alias_prefix=HCA \
```

**Comment by aaclan-ebi** [comment]
Based from this thread (https://embl-ebi-ait.slack.com/archives/C012DG6R1EV/p1592471436114700), please don't do the above testing yet. (You can still test it, but i'll be making more changes by monday so there's a high chance the above way will change)

**Comment by mshadbolt** [comment]
Ok I will run through with the small integration test spreadsheet and post my notes back here when I am finished.

**Comment by clairerye** [comment]
Thanks! And sorry for the confusion and change of communication medium halfway through. I will keep it all in the ticket going forwards!

**Comment by mshadbolt** [comment]
I have added some criteria to test above, do these seem reasonable @aaclan-ebi @clairerye ?

Can you think of any other specific points to test?

**Comment by mshadbolt** [comment]
Other random question, so there is no way for a project that is only archived to get to completed?

**Comment by mshadbolt** [comment]
Hi @aaclan-ebi can you remind me how I upload files into the dev ingest bucket?

I have so far created a submission here: https://ui.ingest.dev.archive.data.humancellatlas.org/submissions/detail?id=5eeb3a7a65490c0f3526627e

Uploaded my files to an hca-util bucket here

but when I use the hca cli to select the ingest dev bucket and the hca util upload area I get the following errors:

```
Starting upload of 5 files to upload area f7632a6a-0bda-4f67-8c75-96e4acef8546

While uploading s3://hca-util-upload-area/65064b84-6214-4d09-a086-fe63571658f6/pbmc4k_1000_S1_L001_I1_001.fastq.gz encountered exception <class 'botocore.exceptions.ClientError'>('An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied',): An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied

While uploading s3://hca-util-upload-area/65064b84-6214-4d09-a086-fe63571658f6/ encountered exception <class 'botocore.exceptions.ClientError'>('An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied',): An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied

While uploading s3://hca-util-upload-area/65064b84-6214-4d09-a086-fe63571658f6/pbmc4k_1000_S1_L001_R2_001.fastq.gz encountered exception <class 'botocore.exceptions.ClientError'>('An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied',): An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied

While uploading s3://hca-util-upload-area/65064b84-6214-4d09-a086-fe63571658f6/pbmc4k_1000_S1_L001_R1_001.fastq.gz encountered exception <class 'botocore.exceptions.ClientError'>('An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied',): An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied

While uploading s3://hca-util-upload-area/65064b84-6214-4d09-a086-fe63571658f6/my_cool_protocol.pdf encountered exception <class 'botocore.exceptions.ClientError'>('An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied',): An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
Traceback (most recent call last):
  File "/home/mshadbolt/hca_cli_env/bin/hca", line 8, in <module>
    sys.exit(main())
  File "/home/mshadbolt/hca_cli_env/lib/python3.5/site-packages/hca/cli.py", line 132, in main
    result = parsed_args.entry_point(parsed_args)
  File "/home/mshadbolt/hca_cli_env/lib/python3.5/site-packages/hca/upload/cli/upload_command.py", line 62, in __init__
    sync=(args.sync))
  File "/home/mshadbolt/hca_cli_env/lib/python3.5/site-packages/hca/upload/upload_area.py", line 137, in upload_files
    raise UploadException(error)
hca.upload.exceptions.UploadException: 
The following files failed:
s3://hca-util-upload-area/65064b84-6214-4d09-a086-fe63571658f6/my_cool_protocol.pdf: [Exception] An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
s3://hca-util-upload-area/65064b84-6214-4d09-a086-fe63571658f6/: [Exception] An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
s3://hca-util-upload-area/65064b84-6214-4d09-a086-fe63571658f6/pbmc4k_1000_S1_L001_I1_001.fastq.gz: [Exception] An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
s3://hca-util-upload-area/65064b84-6214-4d09-a086-fe63571658f6/pbmc4k_1000_S1_L001_R1_001.fastq.gz: [Exception] An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
s3://hca-util-upload-area/65064b84-6214-4d09-a086-fe63571658f6/pbmc4k_1000_S1_L001_R2_001.fastq.gz: [Exception] An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
Please retry or contact an hca administrator at data-help@humancellatlas.org for help.
```

**Comment by aaclan-ebi** [comment]
> Thanks! And sorry for the confusion and change of communication medium halfway through. I will keep it all in the ticket going forwards!

I think slack conversation is fine, just want to keep ticket updated since i wrote some notes for testing archiving but we're not gonna do it. Summary of slack conversation in the ticket is fine.

> Other random question, so there is no way for a project that is only archived to get to completed?
No, since we still want the option to export to dcp we can't delete the files yet. They will stay in `Archived`.

**Comment by aaclan-ebi** [comment]
I added acceptance criteria in the submit to archives only path
> - [ ] User should not be able to submit with "delete upload area" selected

**Comment by mshadbolt** [comment]
... I have submitted already twice with this selected

**Comment by mshadbolt** [comment]
ohh specific to the archiving submission, am testing that one now ...

**Comment by aaclan-ebi** [comment]
Regarding the file upload issue above, it was resolved by reconfiguring back the upload service to allow sourcing from hca-util upload areas. (It was configured differently before for special reason)

**Comment by clairerye** [comment]
That is a good point about remaining in archived state. But we absolutely need this, at least for MVP as all new contributor datasets will need to stay in the archived state between now and when we push them to Terra. And also ongoing until we can have a more automatic way of doing release dates. I wonder if there is a situation (other than getting DCP1 datasets into archives now) when we would want the archived state to go to completed and therefore delete the upload area/data.

**Comment by mshadbolt** [comment]
I have run through all the tests I outlined in the body of the ticket. Everything seemed to work as expected. I have a working directory here: https://drive.google.com/open?id=1WQbdXpbVtDvNy2cxIKqUXjSktIvOTGtx&authuser=mshadbolt%40ebi.ac.uk&usp=drive_fs
And a step by step run through txt file here: https://drive.google.com/open?id=1WT9XpXvM1Ol8Ln1-w9YaHzDeqhLW5ljL&authuser=mshadbolt%40ebi.ac.uk&usp=drive_fs

Some general feedback points:

#### When deciding where to submit to:
- Since we now have the ability NOT to send it to the HCA, we should probably revise the text that says "your data is going to make its way to the Human Cell Atlas pipelines for immediate analysis and release."

- I think we should somehow make it clear what archives the data and metadata will be submitted to. 

- I think we should revise the sentence 'Data will be public immediately', to something like, 'Data will be made public with the next snapshot' or whatever the correct terminology is here. I know we agreed not to implement it this way yet but I think that a contributor might expect that if they set a release date then it would be valid for both when data is released on archives and when data is released in DCP.

- If I can't progress to the cleanup state if I only accession then unticking the submit to HCA option should automatically untick this box too? I see this is implemented as a warning if you try doing it. Maybe consult with Gabs on the best way to approach this? (Or maybe you already did)

#### After Submission:

- I don't get any obvious confirmation or message to tell me what happens next.

- If my project was sent for archiving, how do I get the accession? How long would it take? how do I access the accessions?

- If my project was sent to HCA, when do I see it in the browser? Do I get an HCA identifier?

- In the flow where the project is only submitted to HCA, it seems a bit weird to have the 'Assay Manifests' heading with nothing underneath it.

**Comment by clairerye** [comment]
That's a really great feedback and well documented as a flow through the system. Would you be happy to draft improved text so that it can be updated. 
From reading your feedback, I assume there were no serious bugs/issues, but a series of UX aspects that could be improved?
I think your questions about after submission are very relevant and I don't think we have a particularly good understanding especially with regards to the DCP. I suspect we may have a short term solution for the MVP and a longer term user facing solution ASAP after that. 
Critical info to pass to contributors would be what? Biosamples/Biostudies/ENA accessions and a date for appearance in the DCP2 portal? And UUIDs? or other ids?

**Comment by mshadbolt** [comment]
Yep all the feedback I gave was more if I was putting my 'external user' hat on. As a wrangler I think the system works ok and we gloss over most of the details anyway so they can definitely be worked on for the future rather than right now.

I think the main info the user would want to know is what is the project level accession, so BioStudies and ENA and probably where/when it would show up on the hca browser. BUT I am not sure if for DCP2 we will still be following the same idea with a url with the project url. If we don't really know what that would look like until the snapshot is done and the data is released we could maybe just tell the contributor that we will email them the link to their project on the data browser when it is released?

**Comment by aaclan-ebi** [comment]
Thanks @marion & @clairerye !

I've made some changes in the UI to improve the submission view:

https://github.com/ebi-ait/hca-ebi-dev-team/issues/154#issuecomment-647458216

**Comment by clairerye** [comment]
Brilliant, thank you. I think we can close this ticket now. Further testing when the archiver is deployed can be done on a new ticket.
