### ISSUE TITLE
Review Submission Count

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#244]
There are 15 thousand submission in the ingest database. 
It has been assumed that this is due to valid analysis submission.

- [ ] Check the assumption that submission count is high because of analysis submissions.
- [ ] Check whether analysis submission need to be kept with the move to DCP2.
- [ ] Check for orphaned submission that aren't analysis submissions.

Based on this investigation a new plan will need to be made.

**Comment by lauraclarke** [comment]
@MightyAx is this still relevant?

**Comment by MightyAx** [comment]
Hopefully not, but until we investigate we won't know if it's needed.
For 30ish projects I would expect tens or hundreds of submissions, so it looks like there might be orders of magnitude of redundant data in the system. Might be a just an oddity, might be a symptom of a problem.

**Comment by lauraclarke** [comment]
I am trying to clean up unneeded tasks from the operations board so it can be relevant to what we are doing rather than contain things that we might do something with at some point

Do you know if this is actually causing any issues for anyone? Does this ticket need to exist or can someone just find the time to investigate at some point without it being ticketed!
