### ISSUE TITLE
Check the 17 data sets are represented correctly in the data browser

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-dev-team#303]
The 17 datasets have been exported, imported, snapshotted and indexed in the browser.

Manual checking that the datasets are represented correctly. Please list an issues found in this ticket so we can work out where in the process this might have happened.

Known issue with Peng dataset - how is this represented in the browser? @mshadbolt I think you said some fields were just listed as unspecified. Is there anything else? Can we ask if this is an issue for secondary analysis. 

Portal link: https://dev.singlecell.gi.ucsc.edu/explore/projects?catalog=dcp2ebi

**Acceptance Criteria:**

- [x] all projects checked by @mshadbolt and @ami-day 
- [x] bugs/inconsistencies summarised in a doc
- [x] idea on whether the bugs are caused by incorrect metadata or incorrect indexing

**Comment by mshadbolt** [comment]
I will be summarising my comments for each project here: https://docs.google.com/document/d/19zeQtnyjCGVS49fMODptUBty83MglrCjywo70mCODG8/edit?usp=sharing

**Comment by ami-day** [comment]
I went through each of the projects and almost all the problems I picked up were already identified by @mshadbolt on a per project. I think next time we have a similar task, it would be a better use of our time to split the list into 2 and do half each.
I have summarised the per project comments into different 'types' of problems to help us prioritise which points we might need to address this sprint, and if not all, the points we could keep in mind to improve our work in future sprints.

**Comment by mshadbolt** [comment]
Thanks for the summary Ami. I changed a few things and added a few points that you had missed. The issue with the hindlimb project is actually a metadata issue rather than an export issue, so I moved that one and made a new category for 'metadata tsv issues'.

I think having a two sets of eyes on things like this is very valuable because getting two people's opinions on things that seem confusing, even if they are the same opinion, adds weight to when we make suggestions for improvements. Kind of like when Gabs asks all wranglers to give feedback on the UI, rather than just asking one of us.

I also thought is was a good opportunity for you to see how things get outputted into the portal since I assume you haven't interacted with it much since you started as this is the first time you will have seen how the metadata gets through into the portal. I realise it wasn't the most fun task but I still think it is valuable.

**Comment by ami-day** [comment]
Yea, I understand where you're coming from. It was definitely good to have a better idea of who things are output in the portal but I could have done this when assessing 1/2 the list. 

I agree its helpful have two sets of eyes on things for the reasons you say. **But** my point was more that I don't think having us both do it is  an effective use of 2 people's time (weighing against other prioritises/tasks we could be doing instead). I trust 1 person is sufficient to pick up the obvious problems at this point. I think we will have to agree to disagree here.
