### ISSUE TITLE
Spreadsheet generator bug: "Donor organism: Familial re..." tab is being generated

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-dev-team#312]
"Donor organism – Familial re…" is being added as a separate tab when the ‘donor organism’ TypeSpec is added.

The `familial_relationships` module should be added as columns within the `Donor organism` tab.

~~My understanding is that familial_relationships should be included as a separate stand-alone tab with the tab name: "Familial relationships".~~

**Acceptance crtieria:**

- [x] Code is implemented to fix this issue

- [x] The unit tests are updated to reflect this change

**Comment by mshadbolt** [comment]
> My understanding is that familial_relationships should be included as a separate stand-alone tab with the tab name: "Familial relationships".

Minor change to this, the Familial Relationships module should be included within the Donor organism tab, not as a new tab. So this bug is very similar to what was happening with the 'reagents' module generating a new tab when it should have been inside the respective protocol tab.

I edited the ticket above.

**Comment by mshadbolt** [comment]
I have made a PR to fix this issue here: https://github.com/ebi-ait/ingest-broker/pull/5

**Comment by mshadbolt** [comment]
This has been merged and deployed
