### ISSUE TITLE
[Core] Add State for Archiving

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-dev-team#43]

**Comment by aaclan-ebi** [comment]
Goal is to have a state indicating that the submission is ready to archive.

From dev design discussion today, we agreed to introduce a new submission state:

....  Submitted -> Processing -> *Archiving* -> Cleanup -> Completed

Some changes are needed in Core and State tracker.

**Comment by aaclan-ebi** [comment]
Changes to UI, Core and State tracker are merged to master and deployed to dev env. 

Manual testing done:

Steps:
1. Using Ingest UI, upload the DCP test spreadsheet from metadata-schema repo https://github.com/HumanCellAtlas/metadata-schema/blob/develop/infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx

2. Force set the data files to valid 
curl -X PUT <validating url in submission resource>
curl -X PUT <valid url in submission resource>

3. When submission is valid, hit Submit button

Expected Behaviour:
All bundle manifests are generated and submission is in `Archiving` State
