### ISSUE TITLE
Delete update submissions in Ingest

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#448]
These are submissions that have `isUpdate` property true. 

could use this script: https://github.com/ebi-ait/hca-ebi-dev-team/pull/356/files

The projects with `isUpdate` is true should also be deleted.

**Comment by ESapenaVentura** [comment]
I missed the comments, apologies about that

@Wkt8 these projects need to be deleted because they are remnants of how the update process used to be.

Currently, they are technically invisible and only accessible through the API. We don't need these and they only add confusion to the mix when trying to extract information through the API
