### ISSUE TITLE
Fix duplicate submissions of project 1ad6cee6-53a5-4804-a870-e5bd991186e0 

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#451]
We discovered a dataset that has 2 exported submissions with identical metadata 
https://contribute.data.humancellatlas.org/projects/detail?uuid=1ad6cee6-53a5-4804-a870-e5bd991186e0&tab=upload

According to Will from UCSC:
> there was a miss labelling of read indexes, the first doesn’t have any I1 labels while the second does so I’m guessing the second just missed getting exported.

Both first and second submissions were exported.

We need to 
- [x] to delete the entities from the first submission in the Terra staging area
- [x] @gabsie to tell the Data Import team they have to delete the entities from the first submission and reimport the project staging area with the entities in the second submission (I’m not sure how this will work we haven’t done this before)

**Comment by amnonkhen** [comment]
We need to:
- delete the earlier of the two submissions
- make sure it is also deleted downstream
- include this in the agenda for the post DCP demo discussion

**Comment by jacobwindsor** [comment]
Need to delete this submission fb8e2017-8815-4898-878e-baa4cf116058

**Comment by jacobwindsor** [comment]
Since the submission is part of a project, I have deleted files dated in May with:

`for file in `gsutil ls gs://broad-dsp-monster-hca-prod-ebi-storage/prod/1ad6cee6-53a5-4804-a870-e5bd991186e0/$DIR | grep 2021-05`; do gsutil rm $file; done;`

where `$DIR` is:

- [ ] metadata/donor_organism
- [ ] metadata/cell_line
- [ ] metadata/cell_suspension
- [ ] metadata/collection_protocol
- [ ] metadata/differentiation_protocol
- [ ] metadata/dissociation_protocol
- [ ] metadata/library_preparation_protocol
- [ ] metadata/process
- [ ] metadata/project
- [ ] metadata/sequence_file
- [ ] metadata/sequencing_protocol
- [ ] metadata/specimen_from_organism

**Comment by ofanobilbao** [comment]
Jacob did all he needed to do for this ticket's point 1. 2 needs to be done. @ESapenaVentura will discuss this and 2 other projects in the DCP demo tomorrow so that we are aligned on the way we do this

**Comment by ESapenaVentura** [comment]
AI
- Ask for deletion to Andrew (Data import team)
- re-export to A NEW STAGING AREA
- Fill an import form

**Comment by ESapenaVentura** [comment]
Discussed with @aaclan-ebi :
- [ ] Delete everything in the staging area regarding this project 
- [ ] Re-export submission
- [ ] Confirm with Andrew deletion of project
- [ ] Fill import form

**Comment by ofanobilbao** [comment]
@ESapenaVentura needs to re-validate to re-export

**Comment by ESapenaVentura** [comment]
There's a graph validation issue - Contacted Rachel, Paris and Will to see how we can solve this

**Comment by ami-day** [comment]
Submission has been sent back to valid, but there is an error. There are too many sequence files in a process, need to change lane index so fastq files are grouped together (8 processes, 24 files). @ESapenaVentura is working on this this morning

**Comment by ami-day** [comment]
Moving this ticket to done
