### ISSUE TITLE
Make sure project experiment design graphs are correct

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/hca-ebi-dev-team#455]
https://docs.google.com/document/d/1Kd-hNFqwTDOT0-ZHlbBMC0g2wXcJx1jx3JGf5e0vIWM/edit

**Comment by ESapenaVentura** [comment]
@gabsie do we still need this ticket?

if so, can we make it more specific?

**Comment by ofanobilbao** [comment]
This needs assessing how long it would take

**Comment by ofanobilbao** [comment]
Gabs and me discussed this yesterday. No point doing this now. We will have to run graph validation on old projects as we need to update them. We will address issues as they come rather than do a massive amount of work here, and then have an awful lot of actions to perform, that we might not have capacity to address. Let's do this one by one as needed. Closing the epic and the stories on it.
